In [2]:
import numpy as np
import sys

#BASICS

In [ ]:
#How to initialize Numy array
a = np.array([1,2,3])
print(a)
print("......................................................")
b = np.array([[9.0,8.0,5.0],[4.3,1.0,3]])
print(b)

[1 2 3]
......................................................
[[9.  8.  5. ]
 [4.3 1.  3. ]]


In [ ]:
#Get Dimension
print("Dimension of a",a.ndim)
print("Dimension of b",b.ndim)
print("......................................................")

#Get Shape
print("Shape of a",a.shape)
print("Shape of a",b.shape)
print("......................................................")

#Get to know how much memory occupied by numpy array
#you can also assign "dtype" while creating new numpy array as dtype = in32/int16/int64 
print("data type of a:",a.dtype)
print("data type of b:",b.dtype)

Dimension of a 1
Dimension of b 2
......................................................
Shape of a (3,)
Shape of a (2, 3)
......................................................
data type of a: int64
data type of b: float64


#Accessing/Changing specific elements, rows, columns etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific elemets [row,col]
print(a[1,5])
print(a[1,-2])
print(a[-1,5])

13
13
13


In [ ]:
#Get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [ ]:
#Get a specific columns
a[:,2]

array([ 3, 10])

In [ ]:
#Getting a little more fancy [StartIndex:EndIndex:StepSize]

print(a[0,1:6])
print(a[:,1::2])

[2 3 4 5 6]
[[ 2  4  6]
 [ 9 11 13]]


In [ ]:
#To change something
a[1,5] = 1000
print(a)
a[:,2] = 5000
print(a)

[[   1    2    3    4    5    6    7]
 [   8    9   10   11   12 1000   14]]
[[   1    2    3    4    5    6    7]
 [   8    9   10   11   12 1000   14]]
[[   1    2 5000    4    5    6    7]
 [   8    9 5000   11   12 1000   14]]


#3D example

In [ ]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#Get Specific Element
print(b[0,1,1])


4


In [ ]:
#Replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#Initializing Different Types of Arrays

In [ ]:
#All 0s matrix
c  = np.zeros(5) #One dimension
d = np.zeros((2,3)) #two Dimension
e = np.zeros((2,3,3)) #Three dimension
print(c)
print(d)
print(e)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#All 1s Matrix
f = np.ones((4,2,2), dtype='int32')
f


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#Any other Number
g = np.full((2,2),99)
g

array([[99, 99],
       [99, 99]])

In [ ]:
#Any other number(full_like)
h = np.full_like(g,44)
h

array([[44, 44],
       [44, 44]])

In [ ]:
#Random Decimal numbers between 0-1
i = np.random.rand(4,2,3)
i

array([[[0.44735121, 0.87003733, 0.34768584],
        [0.61543894, 0.12123858, 0.11492033]],

       [[0.21763229, 0.64009018, 0.96767518],
        [0.53853257, 0.45034416, 0.43352085]],

       [[0.69142741, 0.90031137, 0.40467513],
        [0.87750074, 0.67804126, 0.9817577 ]],

       [[0.67867957, 0.40553395, 0.5748594 ],
        [0.77253542, 0.50298477, 0.24735797]]])

In [ ]:
#Random Integer values
j = np.random.randint(7, size = (3,3)) #here we are printing numbers with in 0-7
print(j)
print("__________________________________________________________________________")
 
jj = np.random.randint(3,7, size = (3,3)) #here we are printing numbers with in 3-7
print(jj)

[[2 4 3]
 [3 1 4]
 [3 6 3]]
__________________________________________________________________________
[[5 6 4]
 [4 4 4]
 [5 3 6]]


In [ ]:
#Identity matrix
k = np.identity(4)
k

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#To Repeat the values inside matrix

l = np.array([1,2,3])
repeat_l = np.repeat(l,3,axis = 0)
print(repeat_l)


[1 1 1 2 2 2 3 3 3]


In [ ]:
#LEts do it with 3D
l = np.array([[1,2,3]])
repeat_ll = np.repeat(l,3,axis = 0)
print(repeat_ll)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#Example
#output = 
#[[1,1,1,1,1]
#[1,0,0,0,1]
#[1,0,9,0,1]
#[1,0,0,0,1]
#[1,1,1,1,1]]

In [ ]:
ones = np.ones((5,5), dtype = "int32")
print(ones)

print("++++++++++++++++++++++++++++++++++++++++++++")

zero = np.zeros((3,3), dtype = "int32")
zero[1,1] = 9
print(zero)

print("++++++++++++++++++++++++++++++++++++++++++++")

ones[1:4,1:4]= zero
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
++++++++++++++++++++++++++++++++++++++++++++
[[0 0 0]
 [0 9 0]
 [0 0 0]]
++++++++++++++++++++++++++++++++++++++++++++
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#Be Careful when copying arrays!!!

In [ ]:
#Without using COPY function

a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)

#Values of a is also changed because of numpy standard 

[100   2   3]
[100   2   3]


In [ ]:
#Using COPY function
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)
#Values remains same for a

[100   2   3]
[1 2 3]


#Mathematics

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a+2

array([3, 4, 5, 6, 7])

In [ ]:
a-2

array([-1,  0,  1,  2,  3])

In [ ]:
a*2

array([ 2,  4,  6,  8, 10])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
b = np.array([1,1,1,1,1])
a = a+b
a

array([2, 3, 4, 5, 6])

In [ ]:
#Take the sin/cos
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

#Linear Algebra


In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

#a's column should be equal to b's rows
#We cant multiply both arrays directly
c = np.matmul(a,b)
c

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

#The determinant of a matrix is a special number that can be calculated from a square matrix.

####A Matrix is an array of numbers:

####A Matrix = [3,8
####            4,6]
####(This one has 2 Rows and 2 Columns)

####The determinant of that matrix is:

####3×6 − 8×4 = 18 − 32 = −14

Reference - https://www.mathsisfun.com/algebra/matrix-determinant.html

In [ ]:
#Find the Determinant
d=np.identity(3)
print(d)
np.linalg.det(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#Lot more can be Done

####Determinant
####Trace
####Singular Vector Decomposition
####Eigenvalues
####Matrix Norm
####Inverse
####Etc..

#Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.min(stats,axis=1) #Will give all minimum values of a rows

array([1, 4])

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats) #Can use axis

21

#Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print("shape:",before.shape)

[[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)


In [ ]:
#Reshape the matrix

after = before.reshape((8,1))
after1 = before.reshape((4,2))
after2 = before.reshape((2,2,2))
print(after)
print(after1)
print(after2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#You can repeat stacking
np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
#Horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print("_______________________________________________________________________________")
print(h2)
print("_______________________________________________________________________________")
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
_______________________________________________________________________________
[[0. 0.]
 [0. 0.]]
_______________________________________________________________________________


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#Miscellaneous 

####Load Data from File

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving data_numpy.txt to data_numpy.txt


In [ ]:
uploaded

{'data_numpy.txt': b'1,13,21,11,196,175,4,3,1,34,1,6,1,3685\r\n45,3,1,53,2,6,2,7,3,5,3,2587,3,46,6,13\r\n52,3,6,52,5,63,5,63,6,4,8,9,40,5297,52'}

In [ ]:
data = np.array([[1,13,21,11,196],[2587,3,46,6,13],[8,9,40,5297,52]])
print(data)

[[   1   13   21   11  196]
 [2587    3   46    6   13]
 [   8    9   40 5297   52]]


####Boolean Masking and Advanced indexing

In [ ]:
data>50

array([[False, False, False, False,  True],
       [ True, False, False, False, False],
       [False, False, False,  True,  True]])

In [ ]:
data[data>50]

array([ 196, 2587, 5297,   52])

In [ ]:
##You can index with a list in numPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])

In [ ]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

####INDEXING

In [ ]:
c[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
c[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
x = c[[0,0,4,4,5,5],[3,4,3,4,3,4]]
print(x)

######OORRRRR#######
y = c[[0,4,5],3:]
print(y)

[ 4  5 24 25 29 30]
[[ 4  5]
 [24 25]
 [29 30]]


#Exercises

In [ ]:
print(np.__version__)

1.19.4


In [ ]:
#Create a 1D array of numbers from 0 to 9
oneD = np.arange(10)
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Create a 3x3 numpy array of all True's
boo = np.full((3,3), True, dtype= bool)
print(boo)

#Alternate method
boo1 = np.ones((3,3), dtype = bool)
print(boo1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#Extract all ODD numbers from array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [ ]:
#Replace all ODD numbers in array with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2 == 1] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
#Replace all ODD numbers in arr with -1 without changing original array

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = arr.copy()

out[out %2==1] = -1
print(out)

#Alternate method
out2 = np.where(arr%2==1, -1, arr)
print(out2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#Convert a 1D array to a 2D array with 2 rows
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr1 = arr.reshape(2,5)
print(arr1)

#OR#

arr2 = arr.reshape(2,-1) #Setting to -1 automatically decides the number of cols.
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#Stack arrays a and b vertically

a  = np.arange(10).reshape(2,-1)
print(a)
print("___________________________________________________________________________________")
b = np.repeat(1,10).reshape(2,-1)
print(b)
print("___________________________________________________________________________________")
c = np.vstack((a,b))
print(c)

#OR#
#np.concatenate([a,b],axis =0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
___________________________________________________________________________________
[[1 1 1 1 1]
 [1 1 1 1 1]]
___________________________________________________________________________________
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
##Stack arrays a and b vertically

a  = np.arange(10).reshape(2,-1)
print(a)
print("___________________________________________________________________________________")
b = np.repeat(1,10).reshape(2,-1)
print(b)
print("___________________________________________________________________________________")
c = np.hstack((a,b))
print(c)


#OR#
#np.concatenate([a,b],axis =1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
___________________________________________________________________________________
[[1 1 1 1 1]
 [1 1 1 1 1]]
___________________________________________________________________________________
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])

np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
#Get the common items betwenn a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [ ]:
#From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [ ]:
#Get the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7]),)

In [ ]:
#Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a>=5) & (a<=10))
print(index)
print(a[index])

#OR#
#a[(a>=5) & (a<=10)]

(array([1, 3, 4]),)
[ 6  9 10]


In [ ]:
# Convert the function maxx that works on two scalars, to work on two arrays

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

print(maxx(1, 5))

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes = [float])

pair_max(a,b)

5


array([6., 7., 9., 8., 9., 7., 5.])

In [8]:
#Swap columns 1 and 2 in the array arr

arr = np.arange(9).reshape(3,3)
print(arr)
print("_______________________________________")
print(arr[:,[1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
_______________________________________
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [9]:
#Swap rows 1 and 2 in the array arr

arr = np.arange(9).reshape(3,3)
print(arr)

print(arr[[1,0,2],:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [12]:
#Reverse the rows of a 2D array

arr = np.arange(9).reshape(3,3)
print(arr)
print(".......................Reversed Array......................")
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
.......................Reversed Array......................


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [13]:
#Reverse the columns of a 2D array

arr = np.arange(9).reshape(3,3)
print(arr)
print(".......................Reversed Array......................")
arr[:,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
.......................Reversed Array......................


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [23]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arr = np.random.uniform(5,10,(5,3))
print(arr)

#Create a 2D array of shape 5x3 to contain random numbers between 5 and 10.
arr1 = np.random.randint(5,10,(5,3))
print(arr1)

[[9.36134419 6.35177247 9.14957541]
 [9.9139448  7.09950421 8.95976799]
 [8.37883414 6.48984061 5.12416993]
 [5.40474569 5.75959503 8.03539201]
 [9.88498867 8.77562393 9.76709382]]
[[6 7 9]
 [9 9 5]
 [6 9 8]
 [7 5 9]
 [9 5 8]]


In [30]:
#Print or show only 3 decimal places of the numpy array

arr = np.random.random((5,3))
print(arr)

print(".......LIMIT TO  DECIMAL PLACES.......")

np.set_printoptions(precision=3)
print(arr)

[[0.321 0.225 0.585]
 [0.664 0.931 0.812]
 [0.104 0.527 0.924]
 [0.111 0.716 0.78 ]
 [0.098 0.487 0.648]]
.......LIMIT TO  DECIMAL PLACES.......
[[0.321 0.225 0.585]
 [0.664 0.931 0.812]
 [0.104 0.527 0.924]
 [0.111 0.716 0.78 ]
 [0.098 0.487 0.648]]


In [37]:
#Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Create the random array
np.random.seed(100)

# With the seed reset (every time), the same set of numbers will appear every time.
# If the random seed is not reset, different numbers appear with every invocation:

rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
print("......................PRETTY...............")
np.set_printoptions(suppress = True, precision = 6) #precision is optional
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]
......................PRETTY...............
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [38]:
#Limit the number of items printed in python numpy array "a" to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [47]:
#Print the full numpy array a without truncating.

a = np.arange(15)
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
#Import the iris dataset keeping the text intact.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=",",dtype='object')
#Since we want to retain the species, a text field, I have set the dtype to object
names = ('sepallength','sepalwidth','petallength','petalwidth','species')

iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [56]:
#Extract the text column species from the 1D iris imported in previous question.

#iris[:,4]

#>>>>OR<<<<<<

species = np.array([row[4] for row in iris])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [57]:
#Convert the 1D iris to 2D array iris_2d by omitting the species text field

iris_1d = np.genfromtxt(url,delimiter = ",",dtype = None)
#Since we dont want to retain the species, a text field, I have set the dtype to object

iris_2d = np.genfromtxt(url,delimiter=',',dtype = 'float', usecols=[0,1,2,3])
iris_2d[:4]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [59]:
# Find the mean, median, standard deviation of iris's sepallength (1st column)

sepallength = np.genfromtxt(url,delimiter = ',',dtype = 'float',usecols = [0])
mu,med,sd = np.mean(sepallength),np.median(sepallength),np.std(sepallength)

print("mu:",mu)
print("med:",med)
print("std:",sd)

mu: 5.843333333333334
med: 5.8
std: 0.8253012917851409


In [61]:
# Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1

Smax, Smin = sepallength.max(), sepallength.min()

norm = (sepallength-Smin)/(Smax-Smin)

norm[:5]

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444])

In [63]:
#Compute the softmax score of sepallength.

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

#Percentile scores of a numpy array?

######“Percentile” is in everyday use, but there is no universal definition for it. The most common definition of a percentile is a number where a certain percentage of scores fall below that number. You might know that you scored 67 out of 90 on a test. But that figure has no real meaning unless you know what percentile you fall into. 

######If you know that your score is in the 90th percentile, that means you scored better than 90% of people who took the test.
Percentiles are commonly used to report scores in tests, like the SAT, GRE and LSAT. for example, the 70th percentile on the 2013 GRE was 156. That means if you scored 156 on the exam, your score was better than 70 percent of test takers.

In [64]:
#Find the 5th and 95th percentile of iris's sepallength
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [68]:
#Insert np.nan values at 20 random positions in iris_2d dataset

#Method 1
i,j = np.where(iris_2d)

#i,j contains the row numbers and column numbers of 600 elements of iris
iris_2d[np.random.choice((i),20),np.random.choice((j),20)]=np.nan

print(iris_2d)

[[nan 3.5 1.4 0.2]
 [nan 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  nan 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [nan 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 nan 0.4]
 [4.6 3.6 1.  0.2]
 [nan 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 nan 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  nan 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [71]:
#Find the number and position of missing values in iris_2d's sepallength (1st column)

print("Number of missing values:", np.isnan(iris_2d[:,0]).sum())
print("Position of missing values:", np.where(np.isnan(iris_2d[:,0])))

Number of missing values: 6
Position of missing values: (array([ 0,  1, 15, 23, 84, 96]),)


In [73]:
#Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

filter = (iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris_2d[filter]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, nan],
       [4.9, 2.5, 4.5, 1.7]])

In [74]:
#Select the rows of iris_2d that does not have any nan value
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [77]:
#Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

#Solution 2
from scipy.stats.stats import pearsonr
corr, p_value = pearsonr(iris[:,0],iris[:,2])
print(corr)

# Correlation coef indicates the degree of linear relationship between two numeric variables.
# It can range between -1 to +1.

# The p-value roughly indicates the probability of an uncorrelated system producing 
# datasets that have a correlation at least as extreme as the one computed.
# The lower the p-value (<0.01), stronger is the significance of the relationship.
# It is not an indicator of the strength.

0.8717541573048714


In [ ]:
 #Find out if iris_2d has any missing values.

np.isnan(iris_2d)

#np.isnan(iris_2d).any()

In [ ]:
#Replace all ccurrences of nan with 0 in numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

#iris_2d[np.where(np.isnan(iris_2d)==True)]=0
iris_2d[np.isnan(iris_2d)]=0
iris_2d


In [85]:
#Find the unique values and the count of unique values in iris's species

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#Extract the species column in an array
species = np.array([row.tolist()[4] for row in iris])

#Get the Uniqe values and the counts
np.unique(species, return_counts=True)

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype='|S15')

In [ ]:
#Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#Bin petallength
petal_length_bin = np.digitize(iris[:,2].astype('float'),[0,3,5,10])

#Map it to respective category

label_map = {1: 'small', 2: "medium", 3:"large", 4:"np.nan"}

petal_length_cat = [label_map[x] for x in petal_length_bin]

petal_length_cat


In [90]:
#Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

#Compute volume
sepallength = iris_2d[:,0].astype('float')
petallength = iris_2d[:,2].astype('float')
volume = (np.pi* petallength * (sepallength**2))//3

#Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

#Add the new column
out = np.hstack([iris_2d, volume])

out[:4]



array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa', 38.0],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa', 35.0],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa', 33.0]],
      dtype=object)

In [92]:
#How to do probabilistic sampling in numpy?
#Randomly sample iris's species such that setose is twice the number of versicolor and virginica

#Get the species column
species = iris[:,4]

np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5,0.25,0.25])

print(np.unique(species_out, return_counts = True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36]))


In [93]:
#What is the value of second longest petallength of species setosa

#Get the species and petal length columns
petal_len_setosa = iris[iris[:,4]==b"Iris-setosa", [2]].astype('float')

#Get the second last value
np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [97]:
#How to sort a 2D array by a column
#Sort the iris dataset based on sepallength column.

print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [100]:
#Find the most frequent value of petal length (3rd column) in iris dataset.

vals, counts = np.unique(iris[:,2],return_counts=True)
print(vals)
print(counts)
print(vals[np.argmax(counts)])

[b'1.0' b'1.1' b'1.2' b'1.3' b'1.4' b'1.5' b'1.6' b'1.7' b'1.9' b'3.0'
 b'3.3' b'3.5' b'3.6' b'3.7' b'3.8' b'3.9' b'4.0' b'4.1' b'4.2' b'4.3'
 b'4.4' b'4.5' b'4.6' b'4.7' b'4.8' b'4.9' b'5.0' b'5.1' b'5.2' b'5.3'
 b'5.4' b'5.5' b'5.6' b'5.7' b'5.8' b'5.9' b'6.0' b'6.1' b'6.3' b'6.4'
 b'6.6' b'6.7' b'6.9']
[ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5
  4  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1]
b'1.5'


In [101]:
# Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

np.argwhere(iris[:,3].astype(float)>1.0)[0]

#>>>>OR<<<<
# np.where(iris[:,3].astype(float)>1.0)

array([50])

In [120]:
#From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.random.seed(100)
a = np.random.uniform(1,50,20)
print(np.where(a<10,10, np.where(a>30,30,a)))

[27.626842 14.6401   21.801362 30.       10.       10.       30.
 30.       10.       29.179573 30.       11.250904 10.081083 10.
 11.765177 30.       30.       10.       30.       14.429614]


In [130]:
#Get the positions of top 5 maximum values in a given array a
np.random.seed(100)
a = np.random.uniform(1,50,20)
a
# #Method 1 ( to get the indexes)
# np.argpartition(a,-5)[:5]

# #Method 2(to get the values)
a[a.argsort()][-5:]


array([40.995013, 41.466785, 42.39403 , 44.674776, 48.952565])

In [131]:
#How to compute the row wise counts of all possible values in an array?
# Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
# For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

np.random.seed(100)
arr = np.random.randint(1,11,(6,10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [132]:
###CONTINUE
def counts_of_all_values_rowwise(arr2d):
  #Unique values and its counts row wise
  num_counts_array = [np.unique(row, return_counts=True)for row in arr2d]

  #Count of all values row wise
  return([[int(b[a==i])if i in a else 0 for i in np.unique(arr2d)]for a,b in num_counts_array])

print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [135]:
#Convert array_of_arrays into a flat linear 1d array

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
array_of_arrays = np.array([arr1,arr2,arr3])

print(array_of_arrays)

#Method 01

arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [146]:
#Compute the one-hot encodings (dummy binary variables for each unique value in the array)

np.random.seed(100)
arr = np.random.randint(1,4,size = 6)
print(arr)

#Method 1
# def one_hot_encodings(arr):
#     uniqs = np.unique(arr) #output-->[1,3]
#     out = np.zeros((arr.shape[0], uniqs.shape[0]))
#     for i, k in enumerate(arr):
#         out[i, k-1] = 1
#     return out

# one_hot_encodings(arr)

#Method 2
(arr[:, None] == np.unique(arr)).view(np.int8)

[1 1 1 3 3 1]


array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0]], dtype=int8)

In [148]:
#Create row numbers grouped by a categorical variable. Use the following sample from iris species as input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)


print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']
[0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


In [151]:
#Create group ids based on a given categorical variable. Use the following sample from iris species as input

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small
#> array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
#>        'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica'],
#>       dtype='<U15')
# Solution:
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]
print(output)


[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [158]:
#Find the maximum value in each row of a numpy array 2d

np.random.seed(100)
a = np.random.randint(1,10,[5,3])
print(a)

print("printing max values")
print(np.amax(a, axis =1))

print("printing index of  max values")
print(np.argmax(a, axis =1))

#MEthod 2
print(np.apply_along_axis(np.max, arr = a, axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
printing max values
[9 8 6 3 9]
printing index of  max values
[0 0 2 0 2]


In [159]:
#Compute the min-by-max for each row for given 2d numpy array

np.random.randint(100)
a = np.random.randint(1,10,[5,3])

np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.142857, 0.4     , 0.666667, 0.5     , 0.25    ])

In [163]:
#Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
np.random.seed(100)
a = np.random.randint(0,5,10)
print(a)
#Create an full True array
out = np.full(a.shape[0], True)
print(out)
#Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]
print(unique_positions)
out[unique_positions] = False

print(out)

[0 0 3 0 2 4 2 2 2 2]
[ True  True  True  True  True  True  True  True  True  True]
[0 4 2 5]
[False  True False  True False False  True  True  True  True]


In [167]:
#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

numeric_col = iris[:,1].astype('float') #sepalwidth
grouping_col = iris[:,4] #species

output = []

for group_val in np.unique(grouping_col):
  print(group_val)
  output.append([group_val, numeric_col[grouping_col==group_val].mean()])

print(output)

b'Iris-setosa'
b'Iris-versicolor'
b'Iris-virginica'
[[b'Iris-setosa', 3.418], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.974]]


In [180]:
#Drop all nan values from a 1D numpy array

a = np.array([1,2,3,np.nan,5,6,7,np.nan])

nan = a[np.isnan(a)]
print(nan)
num = a[~np.isnan(a)] #If u use ~, it means it will show opposite ouput for what u asked
print(num)

[nan nan]
[1. 2. 3. 5. 6. 7.]


In [181]:
# Compute the euclidean distance between two arrays a and b

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [182]:
#Find all the peaks(local maxima) in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations
#where, 2 and 5 are the positions of peak values 7 and 6.

array([2, 5])

In [184]:
#Subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?

#Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]
                
print(a_2d - b_1d[:,None])

SyntaxError: ignored

In [188]:
#  Find the index of 5th repetition of number 1 in x.

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n=5
np.where(x==1)[0][n-1]

8

In [190]:
# Convert numpy's datetime64 object to datetime's datetime object

dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [192]:
# Compute the moving average of window size 3, for the given 1D array.

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)
# Method 1
moving_average(Z, n=3).round(2)

# Source: https://stackoverflow.com/questions/14313510/how-to-calculate-moving-average-using-numpy

array:  [8 8 3 7 7 0 4 2 5 2]


array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

In [193]:
# Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [195]:
# To create strides from a given 1D array?
# From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))


[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


#SOURACE - 
https://www.machinelearningplus.com/python/101-numpy-exercises-python/


#THANK YOU

---

